import { Team, Period } from "../components/types";

// APP TEXT
export const APP_TITLE = "HockeyGM Calendar";
export const FOOTER_TEXT = `${new Date().getFullYear()} Built with ♡ by Karel Haapasalo`;
// PAGES TITLE
export const PAGE_TITLE_HOME = "Home";
export const PAGE_TITLE_DASHBOARD = "Dashboard";
export const PAGE_TITLE_GH_PRIVATE = "GitHub Private";
export const PAGE_TITLE_GH_PUBLIC = "GitHub Public";
export const PAGE_TITLE_CODE = "Code Editor";
export const PAGE_TITLE_SETTINGS = "Settings";
// UI CONSTANTS
export const FOOTER_HEIGHT = 30;
export const HEADER_HEIGHT = 60;
export const DRAWER_WIDTH = 250;

// 2021-2022 hokcey gm jaksot
export const PERIODS: Period[] = [
  {
    name: "Jakso 1",
    startDate: new Date("2021-10-12"),
    endDate: new Date("2021-11-15"),
  },
  {
    name: "Jakso 2",
    startDate: new Date("2021-11-15"),
    endDate: new Date("2021-12-29"),
  },
  {
    name: "Jakso 3",
    startDate: new Date("2021-12-30"),
    endDate: new Date("2022-02-02"),
  },
  {
    name: "Jakso 4",
    startDate: new Date("2022-02-03"),
    endDate: new Date("2022-03-27"),
  },
  {
    name: "Jakso 5",
    startDate: new Date("2022-03-28"),
    endDate: new Date("2022-04-29"),
  },
];

export const TEAMS: Team[] = [
  {
    id: 1,
    name: "New Jersey Devils",
    primary: "#CE1126",
    secondary: "#000000",
    text: "#FFFFFF",
    venue: {
      name: "Prudential Center",
      city: "Newark",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "NJD",
    teamName: "Devils",
    locationName: "New Jersey",
  },
  {
    id: 2,
    name: "New York Islanders",
    primary: "#F47D30",
    secondary: "#00539B",
    text: "#FFFFFF",
    venue: {
      name: "UBS Arena",
      city: "Elmont",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "NYI",
    teamName: "Islanders",
    locationName: "New York",
  },
  {
    id: 3,
    name: "New York Rangers",
    primary: "#0038A8",
    secondary: "#CE1126",
    text: "#FFFFFF",
    venue: {
      id: 5054,
      name: "Madison Square Garden",
      city: "New York",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "NYR",
    teamName: "Rangers",
    locationName: "New York",
  },
  {
    id: 4,
    name: "Philadelphia Flyers",
    primary: "#F74902",
    secondary: "#000000",
    text: "#FFFFFF",
    venue: {
      id: 5096,
      name: "Wells Fargo Center",
      city: "Philadelphia",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "PHI",
    teamName: "Flyers",
    locationName: "Philadelphia",
  },
  {
    id: 5,
    name: "Pittsburgh Penguins",
    primary: "#000000",
    secondary: "#CFC493",
    text: "#FCB514",
    venue: {
      id: 5034,
      name: "PPG Paints Arena",
      city: "Pittsburgh",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "PIT",
    teamName: "Penguins",
    locationName: "Pittsburgh",
  },
  {
    id: 6,
    name: "Boston Bruins",
    primary: "#FFB81C",
    secondary: "#000000",
    text: "#FFFFFF",
    venue: {
      id: 5085,
      name: "TD Garden",
      city: "Boston",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "BOS",
    teamName: "Bruins",
    locationName: "Boston",
  },
  {
    id: 7,
    name: "Buffalo Sabres",
    primary: "#003087",
    secondary: "#F3D03E",
    text: "#FFFFFF",
    venue: {
      id: 5039,
      name: "KeyBank Center",
      city: "Buffalo",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "BUF",
    teamName: "Sabres",
    locationName: "Buffalo",
  },
  {
    id: 8,
    name: "Montréal Canadiens",
    primary: "#AF1E2D",
    secondary: "#192168",
    text: "#FFFFFF",
    venue: {
      id: 5028,
      name: "Bell Centre",
      city: "Montréal",
      timeZone: {
        id: "America/Montreal",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "MTL",
    teamName: "Canadiens",
    locationName: "Montréal",
  },
  {
    id: 9,
    name: "Ottawa Senators",
    primary: "#C2912C",
    secondary: "#000000",
    text: "#000000",
    venue: {
      id: 5031,
      name: "Canadian Tire Centre",
      city: "Ottawa",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "OTT",
    teamName: "Senators",
    locationName: "Ottawa",
  },
  {
    id: 10,
    name: "Toronto Maple Leafs",
    primary: "#00205B",
    secondary: "#FFFFFF",
    text: "#FFFFFF",
    venue: {
      name: "Scotiabank Arena",
      city: "Toronto",
      timeZone: {
        id: "America/Toronto",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "TOR",
    teamName: "Maple Leafs",
    locationName: "Toronto",
  },
  {
    id: 12,
    name: "Carolina Hurricanes",
    primary: "#CC0000",
    secondary: "#000000",
    text: "#A2AAAD",
    venue: {
      id: 5066,
      name: "PNC Arena",
      city: "Raleigh",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "CAR",
    teamName: "Hurricanes",
    locationName: "Carolina",
  },
  {
    id: 13,
    name: "Florida Panthers",
    primary: "#B9975B",
    secondary: "#041E42",
    text: "#FFFFFF",
    venue: {
      id: 5027,
      name: "FLA Live Arena",
      city: "Sunrise",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "FLA",
    teamName: "Panthers",
    locationName: "Florida",
  },
  {
    id: 14,
    name: "Tampa Bay Lightning",
    primary: "#002868",
    secondary: "#FFFFFF",
    text: "#FFFFFF",
    venue: {
      name: "AMALIE Arena",
      city: "Tampa",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "TBL",
    teamName: "Lightning",
    locationName: "Tampa Bay",
  },
  {
    id: 15,
    name: "Washington Capitals",
    primary: "#C8102E",
    secondary: "#041E42",
    text: "#FFFFFF",
    venue: {
      id: 5094,
      name: "Capital One Arena",
      city: "Washington",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "WSH",
    teamName: "Capitals",
    locationName: "Washington",
  },
  {
    id: 16,
    name: "Chicago Blackhawks",
    primary: "#000000",
    secondary: "#FFFFFF",
    text: "#FFFFFF",
    venue: {
      id: 5092,
      name: "United Center",
      city: "Chicago",
      timeZone: {
        id: "America/Chicago",
        offset: -5,
        tz: "CDT",
      },
    },
    abbreviation: "CHI",
    teamName: "Blackhawks",
    locationName: "Chicago",
  },
  {
    id: 17,
    name: "Detroit Red Wings",
    primary: "#CE1126",
    secondary: "#FFFFFF",
    text: "#000000",
    venue: {
      id: 5145,
      name: "Little Caesars Arena",
      city: "Detroit",
      timeZone: {
        id: "America/Detroit",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "DET",
    teamName: "Red Wings",
    locationName: "Detroit",
  },
  {
    id: 18,
    name: "Nashville Predators",
    primary: "#FFB81C",
    secondary: "#041E42",
    text: "#FFFFFF",
    venue: {
      id: 5030,
      name: "Bridgestone Arena",
      city: "Nashville",
      timeZone: {
        id: "America/Chicago",
        offset: -5,
        tz: "CDT",
      },
    },
    abbreviation: "NSH",
    teamName: "Predators",
    locationName: "Nashville",
  },
  {
    id: 19,
    name: "St. Louis Blues",
    primary: "#002F87",
    secondary: "#FCB514",
    text: "#FFFFFF",
    venue: {
      id: 5076,
      name: "Enterprise Center",
      city: "St. Louis",
      timeZone: {
        id: "America/Chicago",
        offset: -5,
        tz: "CDT",
      },
    },
    abbreviation: "STL",
    teamName: "Blues",
    locationName: "St. Louis",
  },
  {
    id: 20,
    name: "Calgary Flames",
    primary: "#C8102E",
    secondary: "#F1BE48",
    text: "#FFFFFF",
    venue: {
      id: 5075,
      name: "Scotiabank Saddledome",
      city: "Calgary",
      timeZone: {
        id: "America/Denver",
        offset: -6,
        tz: "MDT",
      },
    },
    abbreviation: "CGY",
    teamName: "Flames",
    locationName: "Calgary",
  },
  {
    id: 21,
    name: "Colorado Avalanche",
    primary: "#6F263D",
    secondary: "#FFFFFF",
    text: "#000000",
    venue: {
      id: 5064,
      name: "Ball Arena",
      city: "Denver",
      timeZone: {
        id: "America/Denver",
        offset: -6,
        tz: "MDT",
      },
    },
    abbreviation: "COL",
    teamName: "Avalanche",
    locationName: "Colorado",
  },
  {
    id: 22,
    name: "Edmonton Oilers",
    primary: "#FF4C00",
    secondary: "#041E42",
    text: "#FFFFFF",
    venue: {
      id: 5100,
      name: "Rogers Place",
      city: "Edmonton",
      timeZone: {
        id: "America/Edmonton",
        offset: -6,
        tz: "MDT",
      },
    },
    abbreviation: "EDM",
    teamName: "Oilers",
    locationName: "Edmonton",
  },
  {
    id: 23,
    name: "Vancouver Canucks",
    primary: "#00843D",
    secondary: "#FFFFFF",
    text: "#00205B",
    venue: {
      id: 5073,
      name: "Rogers Arena",
      city: "Vancouver",
      timeZone: {
        id: "America/Vancouver",
        offset: -7,
        tz: "PDT",
      },
    },
    abbreviation: "VAN",
    teamName: "Canucks",
    locationName: "Vancouver",
  },
  {
    id: 24,
    name: "Anaheim Ducks",
    primary: "#B9975B",
    secondary: "#000000",
    text: "#FFFFFF",
    venue: {
      id: 5046,
      name: "Honda Center",
      city: "Anaheim",
      timeZone: {
        id: "America/Los_Angeles",
        offset: -7,
        tz: "PDT",
      },
    },
    abbreviation: "ANA",
    teamName: "Ducks",
    locationName: "Anaheim",
  },
  {
    id: 25,
    name: "Dallas Stars",
    primary: "#006847",
    secondary: "#FFFFFF",
    text: "#FFFFFF",
    venue: {
      id: 5019,
      name: "American Airlines Center",
      city: "Dallas",
      timeZone: {
        id: "America/Chicago",
        offset: -5,
        tz: "CDT",
      },
    },
    abbreviation: "DAL",
    teamName: "Stars",
    locationName: "Dallas",
  },
  {
    id: 26,
    name: "Los Angeles Kings",
    primary: "#111111",
    secondary: "#FFFFFF",
    text: "#FFFFFF",
    venue: {
      id: 5081,
      name: "STAPLES Center",
      city: "Los Angeles",
      timeZone: {
        id: "America/Los_Angeles",
        offset: -7,
        tz: "PDT",
      },
    },
    abbreviation: "LAK",
    teamName: "Kings",
    locationName: "Los Angeles",
  },
  {
    id: 28,
    name: "San Jose Sharks",
    primary: "#006D75",
    secondary: "#FFFFFF",
    text: "#FFFFFF",
    venue: {
      name: "SAP Center at San Jose",
      city: "San Jose",
      timeZone: {
        id: "America/Los_Angeles",
        offset: -7,
        tz: "PDT",
      },
    },
    abbreviation: "SJS",
    teamName: "Sharks",
    locationName: "San Jose",
  },
  {
    id: 29,
    name: "Columbus Blue Jackets",
    primary: "#002654",
    secondary: "#FFFFF",
    text: "#FFFFFF",
    venue: {
      id: 5059,
      name: "Nationwide Arena",
      city: "Columbus",
      timeZone: {
        id: "America/New_York",
        offset: -4,
        tz: "EDT",
      },
    },
    abbreviation: "CBJ",
    teamName: "Blue Jackets",
    locationName: "Columbus",
  },
  {
    id: 30,
    name: "Minnesota Wild",
    primary: "#154734",
    secondary: "#FFFFFF",
    text: "#FFFFFF",
    venue: {
      id: 5098,
      name: "Xcel Energy Center",
      city: "St. Paul",
      timeZone: {
        id: "America/Chicago",
        offset: -5,
        tz: "CDT",
      },
    },
    abbreviation: "MIN",
    teamName: "Wild",
    locationName: "Minnesota",
  },
  {
    id: 52,
    name: "Winnipeg Jets",
    primary: "#041E42",
    secondary: "#FFFFFF",
    text: "#FFFFFF",
    venue: {
      id: 5058,
      name: "Canada Life Centre",
      city: "Winnipeg",
      timeZone: {
        id: "America/Winnipeg",
        offset: -5,
        tz: "CDT",
      },
    },
    abbreviation: "WPG",
    teamName: "Jets",
    locationName: "Winnipeg",
  },
  {
    id: 53,
    name: "Arizona Coyotes",
    primary: "#8C2633",
    secondary: "#FFFFFF",
    text: "#FFFFFF",
    venue: {
      id: 5043,
      name: "Gila River Arena",
      city: "Glendale",
      timeZone: {
        id: "America/Phoenix",
        offset: -7,
        tz: "MST",
      },
    },
    abbreviation: "ARI",
    teamName: "Coyotes",
    locationName: "Arizona",
  },
  {
    id: 54,
    name: "Vegas Golden Knights",
    primary: "#B4975A",
    secondary: "#000000",
    text: "#FFFFFF",
    venue: {
      id: 5178,
      name: "T-Mobile Arena",
      city: "Las Vegas",
      timeZone: {
        id: "America/Los_Angeles",
        offset: -7,
        tz: "PDT",
      },
    },
    abbreviation: "VGK",
    teamName: "Golden Knights",
    locationName: "Vegas",
  },
  {
    id: 55,
    name: "Seattle Kraken",
    primary: "#99D9D9",
    secondary: "#000000",
    text: "#FFFFFF",
    venue: {
      name: "Climate Pledge Arena",
      city: "Seattle",
      timeZone: {
        id: "America/Los_Angeles",
        offset: -7,
        tz: "PDT",
      },
    },
    abbreviation: "SEA",
    teamName: "Kraken",
    locationName: "Seattle",
  },
];
